version: "3"
services:
  poll:
    build: "poll/."
    ports:
      - "5000:80"
  redis:
    image: "redis"
    ports:
      - "6379"
  
  worker:
    build: "worker/."
  
  db:
    image: "postgres"

  result:
    build: "result/."
    ports:
      - "5001:80"